# ----------------------------------------------------------------------------
# Copyright (c) 2020 Legorooj <legorooj@protonmail.com>
# Copyright (c) 2020 FluffyKoalas <github.com/fluffykoalas>
# This file and all others in this project are licensed under the MIT license.
# Please see the LICENSE file in the root of this repository for more details.
# ----------------------------------------------------------------------------

trigger:
- dev
- master
- "*"

pr:
  branches:
    include:
    - dev
    - master


jobs: 
- job: "StyleCheck"
  displayName: "Code Style Check (flake8)"
  pool:
    vmImage: "ubuntu-18.04"

  steps:  
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
      architecture: 'x64'

  - script: pip install flake8
    displayName: "Install flake8"

  - script: flake8 sloth
    displayName: "Run style check"

- job: "RunTests"
  pool:
    vmImage: "ubuntu-18.04"
  strategy:
    matrix:
      Python35:
        pythonVersion: 3.5
      Python36:
        pythonVersion: 3.6
      Python37:
        pythonVersion: 3.7
      Python38:
        pythonVersion: 3.8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
      addToPath: true
      architecture: 'x64'
  - script: pip install -r tests/test-requirements.txt -r requirements.txt
    displayName: "Install requirements"
  - script: pytest --maxfail=3 tests --cov=sloth
    displayName: "Run the tests"
  - script: pip install codecov && codecov -e $(pythonVersion) -t $(CODE_COV_TOKEN)
    displayName: "Upload coverage to CodeCov"
    condition: succeeded()
